/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.ui;

import com.google.inject.Injector;
import edu.ufcg.compiladores.pascal.ui.internal.PascalActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PascalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PascalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PascalActivator.getInstance().getInjector(PascalActivator.EDU_UFCG_COMPILADORES_PASCAL_PASCAL);
	}
	
}
