/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal;

import edu.ufcg.compiladores.pascal.PascalStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {
  public static void doSetup() {
    PascalStandaloneSetup _pascalStandaloneSetup = new PascalStandaloneSetup();
    _pascalStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
