/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal;

import edu.ufcg.compiladores.pascal.AbstractPascalRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalRuntimeModule extends AbstractPascalRuntimeModule {
}
