/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.idea.lang;

import edu.ufcg.compiladores.pascal.idea.lang.AbstractPascalFileType;

@SuppressWarnings("all")
public class PascalFileType extends AbstractPascalFileType {
  public final static PascalFileType INSTANCE = new PascalFileType();
  
  public PascalFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(PascalLanguage) is undefined");
  }
}
