/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.web;

import java.util.List;
import java.util.concurrent.ExecutorService;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
/* @WebServlet(, ) */@SuppressWarnings("all")
public class PascalServlet /* implements XtextServlet  */{
  private final List<ExecutorService> executorServices /* Skipped initializer because of errors */;
  
  @Override
  public Object init() {
    throw new Error("Unresolved compilation problems:"
      + "\nProvider cannot be resolved to a type."
      + "\nThe method or field super is undefined"
      + "\n=> cannot be resolved."
      + "\n+= cannot be resolved."
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type PascalWebSetup"
      + "\nInvalid number of arguments. The constructor PascalWebSetup() is not applicable for the arguments (Provider)"
      + "\ninit cannot be resolved");
  }
  
  @Override
  public Object destroy() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\ndestroy cannot be resolved");
  }
}
