/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PascalUiModule extends AbstractPascalUiModule {
}
