/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.idea.lang.pom;

import edu.ufcg.compiladores.pascal.idea.lang.PascalLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class PascalPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public PascalPomDeclarationSearcher() {
		super(PascalLanguage.INSTANCE);
	}
}
