/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.pascal.impl;

import edu.ufcg.compiladores.pascal.pascal.PascalPackage;
import edu.ufcg.compiladores.pascal.pascal.type;
import edu.ufcg.compiladores.pascal.pascal.var_list;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>var list</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl#getVar_id <em>Var id</em>}</li>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl#getVar_ids <em>Var ids</em>}</li>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl#getVar_type <em>Var type</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class var_listImpl extends MinimalEObjectImpl.Container implements var_list
{
  /**
   * The default value of the '{@link #getVar_id() <em>Var id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_id()
   * @generated
   * @ordered
   */
  protected static final String VAR_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar_id() <em>Var id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_id()
   * @generated
   * @ordered
   */
  protected String var_id = VAR_ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getVar_ids() <em>Var ids</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_ids()
   * @generated
   * @ordered
   */
  protected EList<String> var_ids;

  /**
   * The default value of the '{@link #getVar_type() <em>Var type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_type()
   * @generated
   * @ordered
   */
  protected static final type VAR_TYPE_EDEFAULT = type.BOOLEAN;

  /**
   * The cached value of the '{@link #getVar_type() <em>Var type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_type()
   * @generated
   * @ordered
   */
  protected type var_type = VAR_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected var_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.VAR_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVar_id()
  {
    return var_id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar_id(String newVar_id)
  {
    String oldVar_id = var_id;
    var_id = newVar_id;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.VAR_LIST__VAR_ID, oldVar_id, var_id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getVar_ids()
  {
    if (var_ids == null)
    {
      var_ids = new EDataTypeEList<String>(String.class, this, PascalPackage.VAR_LIST__VAR_IDS);
    }
    return var_ids;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public type getVar_type()
  {
    return var_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar_type(type newVar_type)
  {
    type oldVar_type = var_type;
    var_type = newVar_type == null ? VAR_TYPE_EDEFAULT : newVar_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.VAR_LIST__VAR_TYPE, oldVar_type, var_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_LIST__VAR_ID:
        return getVar_id();
      case PascalPackage.VAR_LIST__VAR_IDS:
        return getVar_ids();
      case PascalPackage.VAR_LIST__VAR_TYPE:
        return getVar_type();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_LIST__VAR_ID:
        setVar_id((String)newValue);
        return;
      case PascalPackage.VAR_LIST__VAR_IDS:
        getVar_ids().clear();
        getVar_ids().addAll((Collection<? extends String>)newValue);
        return;
      case PascalPackage.VAR_LIST__VAR_TYPE:
        setVar_type((type)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_LIST__VAR_ID:
        setVar_id(VAR_ID_EDEFAULT);
        return;
      case PascalPackage.VAR_LIST__VAR_IDS:
        getVar_ids().clear();
        return;
      case PascalPackage.VAR_LIST__VAR_TYPE:
        setVar_type(VAR_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_LIST__VAR_ID:
        return VAR_ID_EDEFAULT == null ? var_id != null : !VAR_ID_EDEFAULT.equals(var_id);
      case PascalPackage.VAR_LIST__VAR_IDS:
        return var_ids != null && !var_ids.isEmpty();
      case PascalPackage.VAR_LIST__VAR_TYPE:
        return var_type != VAR_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (var_id: ");
    result.append(var_id);
    result.append(", var_ids: ");
    result.append(var_ids);
    result.append(", var_type: ");
    result.append(var_type);
    result.append(')');
    return result.toString();
  }

} //var_listImpl
