/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.pascal.impl;

import edu.ufcg.compiladores.pascal.pascal.PascalPackage;
import edu.ufcg.compiladores.pascal.pascal.type;
import edu.ufcg.compiladores.pascal.pascal.var_decl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>var decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl#getVar_id <em>Var id</em>}</li>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl#getVar_type <em>Var type</em>}</li>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl#getValue <em>Value</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class var_declImpl extends MinimalEObjectImpl.Container implements var_decl
{
  /**
   * The default value of the '{@link #getVar_id() <em>Var id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_id()
   * @generated
   * @ordered
   */
  protected static final String VAR_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar_id() <em>Var id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_id()
   * @generated
   * @ordered
   */
  protected String var_id = VAR_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getVar_type() <em>Var type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_type()
   * @generated
   * @ordered
   */
  protected static final type VAR_TYPE_EDEFAULT = type.BOOLEAN;

  /**
   * The cached value of the '{@link #getVar_type() <em>Var type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_type()
   * @generated
   * @ordered
   */
  protected type var_type = VAR_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected var_declImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.VAR_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVar_id()
  {
    return var_id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar_id(String newVar_id)
  {
    String oldVar_id = var_id;
    var_id = newVar_id;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.VAR_DECL__VAR_ID, oldVar_id, var_id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public type getVar_type()
  {
    return var_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar_type(type newVar_type)
  {
    type oldVar_type = var_type;
    var_type = newVar_type == null ? VAR_TYPE_EDEFAULT : newVar_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.VAR_DECL__VAR_TYPE, oldVar_type, var_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.VAR_DECL__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_DECL__VAR_ID:
        return getVar_id();
      case PascalPackage.VAR_DECL__VAR_TYPE:
        return getVar_type();
      case PascalPackage.VAR_DECL__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_DECL__VAR_ID:
        setVar_id((String)newValue);
        return;
      case PascalPackage.VAR_DECL__VAR_TYPE:
        setVar_type((type)newValue);
        return;
      case PascalPackage.VAR_DECL__VALUE:
        setValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_DECL__VAR_ID:
        setVar_id(VAR_ID_EDEFAULT);
        return;
      case PascalPackage.VAR_DECL__VAR_TYPE:
        setVar_type(VAR_TYPE_EDEFAULT);
        return;
      case PascalPackage.VAR_DECL__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.VAR_DECL__VAR_ID:
        return VAR_ID_EDEFAULT == null ? var_id != null : !VAR_ID_EDEFAULT.equals(var_id);
      case PascalPackage.VAR_DECL__VAR_TYPE:
        return var_type != VAR_TYPE_EDEFAULT;
      case PascalPackage.VAR_DECL__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (var_id: ");
    result.append(var_id);
    result.append(", var_type: ");
    result.append(var_type);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //var_declImpl
