/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PascalGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PascalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.Pascal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHeadAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cHeadProgramParserRuleCall_0_0 = (RuleCall)cHeadAssignment_0.eContents().get(0);
		private final Assignment cDeclarationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDeclarationsVar_declParserRuleCall_1_0 = (RuleCall)cDeclarationsAssignment_1.eContents().get(0);
		private final Assignment cScopeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cScopeAtribParserRuleCall_2_0 = (RuleCall)cScopeAssignment_2.eContents().get(0);
		
		//Pascal:
		//	(head=program declarations+=var_decl* scope+=atrib*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//(head=program declarations+=var_decl* scope+=atrib*)?
		public Group getGroup() { return cGroup; }
		
		//head=program
		public Assignment getHeadAssignment_0() { return cHeadAssignment_0; }
		
		//program
		public RuleCall getHeadProgramParserRuleCall_0_0() { return cHeadProgramParserRuleCall_0_0; }
		
		//declarations+=var_decl*
		public Assignment getDeclarationsAssignment_1() { return cDeclarationsAssignment_1; }
		
		//var_decl
		public RuleCall getDeclarationsVar_declParserRuleCall_1_0() { return cDeclarationsVar_declParserRuleCall_1_0; }
		
		//scope+=atrib*
		public Assignment getScopeAssignment_2() { return cScopeAssignment_2; }
		
		//atrib
		public RuleCall getScopeAtribParserRuleCall_2_0() { return cScopeAtribParserRuleCall_2_0; }
	}
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//program:
		//	"program" name=ID ";";
		@Override public ParserRule getRule() { return rule; }
		
		//"program" name=ID ";"
		public Group getGroup() { return cGroup; }
		
		//"program"
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class Var_declElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.var_decl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cVar_listAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cVar_listVar_listParserRuleCall_1_0_0 = (RuleCall)cVar_listAssignment_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cTypeAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cTypeTypeEnumRuleCall_1_2_0 = (RuleCall)cTypeAssignment_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//var_decl:
		//	"var" (var_list+=var_list ":" type+=Type ";")+;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" (var_list+=var_list ":" type+=Type ";")+
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//(var_list+=var_list ":" type+=Type ";")+
		public Group getGroup_1() { return cGroup_1; }
		
		//var_list+=var_list
		public Assignment getVar_listAssignment_1_0() { return cVar_listAssignment_1_0; }
		
		//var_list
		public RuleCall getVar_listVar_listParserRuleCall_1_0_0() { return cVar_listVar_listParserRuleCall_1_0_0; }
		
		//":"
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }
		
		//type+=Type
		public Assignment getTypeAssignment_1_2() { return cTypeAssignment_1_2; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_1_2_0() { return cTypeTypeEnumRuleCall_1_2_0; }
		
		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
	}
	public class Var_listElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.var_list");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cIdentifierAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cIdentifierIDTerminalRuleCall_0_0 = (RuleCall)cIdentifierAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cIdentifierAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cIdentifierIDTerminalRuleCall_1_0_0 = (RuleCall)cIdentifierAssignment_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cVarsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cVarsVar_listParserRuleCall_1_2_0 = (RuleCall)cVarsAssignment_1_2.eContents().get(0);
		
		//var_list:
		//	identifier+=ID | identifier+=ID "," vars+=var_list+;
		@Override public ParserRule getRule() { return rule; }
		
		//identifier+=ID | identifier+=ID "," vars+=var_list+
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//identifier+=ID
		public Assignment getIdentifierAssignment_0() { return cIdentifierAssignment_0; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0_0() { return cIdentifierIDTerminalRuleCall_0_0; }
		
		//identifier+=ID "," vars+=var_list+
		public Group getGroup_1() { return cGroup_1; }
		
		//identifier+=ID
		public Assignment getIdentifierAssignment_1_0() { return cIdentifierAssignment_1_0; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_1_0_0() { return cIdentifierIDTerminalRuleCall_1_0_0; }
		
		//","
		public Keyword getCommaKeyword_1_1() { return cCommaKeyword_1_1; }
		
		//vars+=var_list+
		public Assignment getVarsAssignment_1_2() { return cVarsAssignment_1_2; }
		
		//var_list
		public RuleCall getVarsVar_listParserRuleCall_1_2_0() { return cVarsVar_listParserRuleCall_1_2_0; }
	}
	public class AtribElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.atrib");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIdentifierAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIdentifierIDTerminalRuleCall_0_0 = (RuleCall)cIdentifierAssignment_0.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpExpressionParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//atrib:
		//	identifier=ID ":=" exp=expression ";";
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID ":=" exp=expression ";"
		public Group getGroup() { return cGroup; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_0() { return cIdentifierAssignment_0; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0_0() { return cIdentifierIDTerminalRuleCall_0_0; }
		
		//":="
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//exp=expression
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }
		
		//expression
		public RuleCall getExpExpressionParserRuleCall_2_0() { return cExpExpressionParserRuleCall_2_0; }
		
		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValueSomeValueParserRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Assignment cExpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpSecondExpParserRuleCall_1_0 = (RuleCall)cExpAssignment_1.eContents().get(0);
		
		//expression:
		//	value=SomeValue exp+=secondExp*;
		@Override public ParserRule getRule() { return rule; }
		
		//value=SomeValue exp+=secondExp*
		public Group getGroup() { return cGroup; }
		
		//value=SomeValue
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//SomeValue
		public RuleCall getValueSomeValueParserRuleCall_0_0() { return cValueSomeValueParserRuleCall_0_0; }
		
		//exp+=secondExp*
		public Assignment getExpAssignment_1() { return cExpAssignment_1; }
		
		//secondExp
		public RuleCall getExpSecondExpParserRuleCall_1_0() { return cExpSecondExpParserRuleCall_1_0; }
	}
	public class SecondExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.secondExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOpAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOpOperatorParserRuleCall_0_0 = (RuleCall)cOpAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSomeValueParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpSecondExpParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		
		//secondExp:
		//	op=operator value=SomeValue exp+=secondExp*;
		@Override public ParserRule getRule() { return rule; }
		
		//op=operator value=SomeValue exp+=secondExp*
		public Group getGroup() { return cGroup; }
		
		//op=operator
		public Assignment getOpAssignment_0() { return cOpAssignment_0; }
		
		//operator
		public RuleCall getOpOperatorParserRuleCall_0_0() { return cOpOperatorParserRuleCall_0_0; }
		
		//value=SomeValue
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//SomeValue
		public RuleCall getValueSomeValueParserRuleCall_1_0() { return cValueSomeValueParserRuleCall_1_0; }
		
		//exp+=secondExp*
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }
		
		//secondExp
		public RuleCall getExpSecondExpParserRuleCall_2_0() { return cExpSecondExpParserRuleCall_2_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cArit_opParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRel_opParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//operator:
		//	arit_op | rel_op;
		@Override public ParserRule getRule() { return rule; }
		
		//arit_op | rel_op
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//arit_op
		public RuleCall getArit_opParserRuleCall_0() { return cArit_opParserRuleCall_0; }
		
		//rel_op
		public RuleCall getRel_opParserRuleCall_1() { return cRel_opParserRuleCall_1; }
	}
	public class Arit_opElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.arit_op");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cDivKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cModKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//arit_op:
		//	"+" | "-" | "*" | "div" | "mod";
		@Override public ParserRule getRule() { return rule; }
		
		//"+" | "-" | "*" | "div" | "mod"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"+"
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//"*"
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//"div"
		public Keyword getDivKeyword_3() { return cDivKeyword_3; }
		
		//"mod"
		public Keyword getModKeyword_4() { return cModKeyword_4; }
	}
	public class Rel_opElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.rel_op");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cGreaterThanSignEqualsSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLessThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cLessThanSignGreaterThanSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//rel_op:
		//	">" | "<" | ">=" | "<=" | "=" | "<>";
		@Override public ParserRule getRule() { return rule; }
		
		//">" | "<" | ">=" | "<=" | "=" | "<>"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//">"
		public Keyword getGreaterThanSignKeyword_0() { return cGreaterThanSignKeyword_0; }
		
		//"<"
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_2() { return cGreaterThanSignEqualsSignKeyword_2; }
		
		//"<="
		public Keyword getLessThanSignEqualsSignKeyword_3() { return cLessThanSignEqualsSignKeyword_3; }
		
		//"="
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//"<>"
		public Keyword getLessThanSignGreaterThanSignKeyword_5() { return cLessThanSignGreaterThanSignKeyword_5; }
	}
	public class SomeValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.SomeValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//SomeValue:
		//	ID | INT | STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//ID | INT | STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2() { return cSTRINGTerminalRuleCall_2; }
	}
	
	public class TypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "edu.ufcg.compiladores.pascal.Pascal.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBOOLEANBooleanKeyword_0_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINTEGEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINTEGERIntegerKeyword_1_0 = (Keyword)cINTEGEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSTRINGStringKeyword_2_0 = (Keyword)cSTRINGEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Type:
		//	BOOLEAN="boolean" | INTEGER="integer" | STRING="string";
		public EnumRule getRule() { return rule; }
		
		//BOOLEAN="boolean" | INTEGER="integer" | STRING="string"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BOOLEAN="boolean"
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_0() { return cBOOLEANEnumLiteralDeclaration_0; }
		
		//"boolean"
		public Keyword getBOOLEANBooleanKeyword_0_0() { return cBOOLEANBooleanKeyword_0_0; }
		
		//INTEGER="integer"
		public EnumLiteralDeclaration getINTEGEREnumLiteralDeclaration_1() { return cINTEGEREnumLiteralDeclaration_1; }
		
		//"integer"
		public Keyword getINTEGERIntegerKeyword_1_0() { return cINTEGERIntegerKeyword_1_0; }
		
		//STRING="string"
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_2() { return cSTRINGEnumLiteralDeclaration_2; }
		
		//"string"
		public Keyword getSTRINGStringKeyword_2_0() { return cSTRINGStringKeyword_2_0; }
	}
	
	private final PascalElements pPascal;
	private final ProgramElements pProgram;
	private final Var_declElements pVar_decl;
	private final Var_listElements pVar_list;
	private final TypeElements eType;
	private final AtribElements pAtrib;
	private final ExpressionElements pExpression;
	private final SecondExpElements pSecondExp;
	private final OperatorElements pOperator;
	private final Arit_opElements pArit_op;
	private final Rel_opElements pRel_op;
	private final SomeValueElements pSomeValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PascalGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPascal = new PascalElements();
		this.pProgram = new ProgramElements();
		this.pVar_decl = new Var_declElements();
		this.pVar_list = new Var_listElements();
		this.eType = new TypeElements();
		this.pAtrib = new AtribElements();
		this.pExpression = new ExpressionElements();
		this.pSecondExp = new SecondExpElements();
		this.pOperator = new OperatorElements();
		this.pArit_op = new Arit_opElements();
		this.pRel_op = new Rel_opElements();
		this.pSomeValue = new SomeValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("edu.ufcg.compiladores.pascal.Pascal".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Pascal:
	//	(head=program declarations+=var_decl* scope+=atrib*)?;
	public PascalElements getPascalAccess() {
		return pPascal;
	}
	
	public ParserRule getPascalRule() {
		return getPascalAccess().getRule();
	}
	
	//program:
	//	"program" name=ID ";";
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//var_decl:
	//	"var" (var_list+=var_list ":" type+=Type ";")+;
	public Var_declElements getVar_declAccess() {
		return pVar_decl;
	}
	
	public ParserRule getVar_declRule() {
		return getVar_declAccess().getRule();
	}
	
	//var_list:
	//	identifier+=ID | identifier+=ID "," vars+=var_list+;
	public Var_listElements getVar_listAccess() {
		return pVar_list;
	}
	
	public ParserRule getVar_listRule() {
		return getVar_listAccess().getRule();
	}
	
	//enum Type:
	//	BOOLEAN="boolean" | INTEGER="integer" | STRING="string";
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//atrib:
	//	identifier=ID ":=" exp=expression ";";
	public AtribElements getAtribAccess() {
		return pAtrib;
	}
	
	public ParserRule getAtribRule() {
		return getAtribAccess().getRule();
	}
	
	//expression:
	//	value=SomeValue exp+=secondExp*;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//secondExp:
	//	op=operator value=SomeValue exp+=secondExp*;
	public SecondExpElements getSecondExpAccess() {
		return pSecondExp;
	}
	
	public ParserRule getSecondExpRule() {
		return getSecondExpAccess().getRule();
	}
	
	//operator:
	//	arit_op | rel_op;
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//arit_op:
	//	"+" | "-" | "*" | "div" | "mod";
	public Arit_opElements getArit_opAccess() {
		return pArit_op;
	}
	
	public ParserRule getArit_opRule() {
		return getArit_opAccess().getRule();
	}
	
	//rel_op:
	//	">" | "<" | ">=" | "<=" | "=" | "<>";
	public Rel_opElements getRel_opAccess() {
		return pRel_op;
	}
	
	public ParserRule getRel_opRule() {
		return getRel_opAccess().getRule();
	}
	
	//SomeValue:
	//	ID | INT | STRING;
	public SomeValueElements getSomeValueAccess() {
		return pSomeValue;
	}
	
	public ParserRule getSomeValueRule() {
		return getSomeValueAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
