/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractPascalCompletionContributor extends TerminalsCompletionContributor {
	public AbstractPascalCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
