/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class PascalFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
