/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.pascal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>arit expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.arit_expression#getValue <em>Value</em>}</li>
 *   <li>{@link edu.ufcg.compiladores.pascal.pascal.arit_expression#getExp <em>Exp</em>}</li>
 * </ul>
 * </p>
 *
 * @see edu.ufcg.compiladores.pascal.pascal.PascalPackage#getarit_expression()
 * @model
 * @generated
 */
public interface arit_expression extends expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see edu.ufcg.compiladores.pascal.pascal.PascalPackage#getarit_expression_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link edu.ufcg.compiladores.pascal.pascal.arit_expression#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference list.
   * The list contents are of type {@link edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference list.
   * @see edu.ufcg.compiladores.pascal.pascal.PascalPackage#getarit_expression_Exp()
   * @model containment="true"
   * @generated
   */
  EList<repetitive_arit_expression> getExp();

} // arit_expression
