/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ufcg.compiladores.pascal.pascal.PascalPackage#getexpression()
 * @model
 * @generated
 */
public interface expression extends EObject
{
} // expression
