/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.pascal;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.ufcg.compiladores.pascal.pascal.PascalFactory
 * @model kind="package"
 * @generated
 */
public interface PascalPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pascal";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufcg.edu/compiladores/pascal/Pascal";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pascal";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PascalPackage eINSTANCE = edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.PascalImpl <em>Pascal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getPascal()
   * @generated
   */
  int PASCAL = 0;

  /**
   * The feature id for the '<em><b>Head</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASCAL__HEAD = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASCAL__DECLARATIONS = 1;

  /**
   * The feature id for the '<em><b>Scope</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASCAL__SCOPE = 2;

  /**
   * The number of structural features of the '<em>Pascal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASCAL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.programImpl <em>program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.programImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getprogram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The number of structural features of the '<em>program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_blockImpl <em>var block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.var_blockImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_block()
   * @generated
   */
  int VAR_BLOCK = 2;

  /**
   * The feature id for the '<em><b>Var statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_BLOCK__VAR_STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>var block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl <em>var decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_decl()
   * @generated
   */
  int VAR_DECL = 3;

  /**
   * The feature id for the '<em><b>Var id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__VAR_ID = 0;

  /**
   * The feature id for the '<em><b>Var type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__VAR_TYPE = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__VALUE = 2;

  /**
   * The number of structural features of the '<em>var decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl <em>var list</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_list()
   * @generated
   */
  int VAR_LIST = 4;

  /**
   * The feature id for the '<em><b>Var id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_LIST__VAR_ID = 0;

  /**
   * The feature id for the '<em><b>Var ids</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_LIST__VAR_IDS = 1;

  /**
   * The feature id for the '<em><b>Var type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_LIST__VAR_TYPE = 2;

  /**
   * The number of structural features of the '<em>var list</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_LIST_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.blockImpl <em>block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.blockImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getblock()
   * @generated
   */
  int BLOCK = 5;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.statementImpl <em>statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.statementImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getstatement()
   * @generated
   */
  int STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Atrib block</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__ATRIB_BLOCK = 0;

  /**
   * The number of structural features of the '<em>statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.atribImpl <em>atrib</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.atribImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getatrib()
   * @generated
   */
  int ATRIB = 7;

  /**
   * The feature id for the '<em><b>Var id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VAR_ID = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__EXP = 1;

  /**
   * The number of structural features of the '<em>atrib</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.expressionImpl <em>expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.expressionImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getexpression()
   * @generated
   */
  int EXPRESSION = 8;

  /**
   * The number of structural features of the '<em>expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.arit_expressionImpl <em>arit expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.arit_expressionImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getarit_expression()
   * @generated
   */
  int ARIT_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARIT_EXPRESSION__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARIT_EXPRESSION__EXP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>arit expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARIT_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.repetitive_arit_expressionImpl <em>repetitive arit expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.repetitive_arit_expressionImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getrepetitive_arit_expression()
   * @generated
   */
  int REPETITIVE_ARIT_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPETITIVE_ARIT_EXPRESSION__OP = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPETITIVE_ARIT_EXPRESSION__VALUE = 1;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPETITIVE_ARIT_EXPRESSION__EXP = 2;

  /**
   * The number of structural features of the '<em>repetitive arit expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPETITIVE_ARIT_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.rel_expressionImpl <em>rel expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.impl.rel_expressionImpl
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getrel_expression()
   * @generated
   */
  int REL_EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Open</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION__OPEN = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>First</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION__FIRST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Second</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION__SECOND = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Close</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION__CLOSE = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>rel expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link edu.ufcg.compiladores.pascal.pascal.type <em>type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ufcg.compiladores.pascal.pascal.type
   * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#gettype()
   * @generated
   */
  int TYPE = 12;


  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.Pascal <em>Pascal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pascal</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.Pascal
   * @generated
   */
  EClass getPascal();

  /**
   * Returns the meta object for the containment reference '{@link edu.ufcg.compiladores.pascal.pascal.Pascal#getHead <em>Head</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Head</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.Pascal#getHead()
   * @see #getPascal()
   * @generated
   */
  EReference getPascal_Head();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.Pascal#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.Pascal#getDeclarations()
   * @see #getPascal()
   * @generated
   */
  EReference getPascal_Declarations();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.Pascal#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scope</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.Pascal#getScope()
   * @see #getPascal()
   * @generated
   */
  EReference getPascal_Scope();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.program <em>program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>program</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.program
   * @generated
   */
  EClass getprogram();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.program#getName()
   * @see #getprogram()
   * @generated
   */
  EAttribute getprogram_Name();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.var_block <em>var block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>var block</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_block
   * @generated
   */
  EClass getvar_block();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.var_block#getVar_statements <em>Var statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var statements</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_block#getVar_statements()
   * @see #getvar_block()
   * @generated
   */
  EReference getvar_block_Var_statements();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.var_decl <em>var decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>var decl</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_decl
   * @generated
   */
  EClass getvar_decl();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.var_decl#getVar_id <em>Var id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var id</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_decl#getVar_id()
   * @see #getvar_decl()
   * @generated
   */
  EAttribute getvar_decl_Var_id();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.var_decl#getVar_type <em>Var type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var type</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_decl#getVar_type()
   * @see #getvar_decl()
   * @generated
   */
  EAttribute getvar_decl_Var_type();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.var_decl#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_decl#getValue()
   * @see #getvar_decl()
   * @generated
   */
  EAttribute getvar_decl_Value();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.var_list <em>var list</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>var list</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_list
   * @generated
   */
  EClass getvar_list();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.var_list#getVar_id <em>Var id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var id</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_list#getVar_id()
   * @see #getvar_list()
   * @generated
   */
  EAttribute getvar_list_Var_id();

  /**
   * Returns the meta object for the attribute list '{@link edu.ufcg.compiladores.pascal.pascal.var_list#getVar_ids <em>Var ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Var ids</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_list#getVar_ids()
   * @see #getvar_list()
   * @generated
   */
  EAttribute getvar_list_Var_ids();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.var_list#getVar_type <em>Var type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var type</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.var_list#getVar_type()
   * @see #getvar_list()
   * @generated
   */
  EAttribute getvar_list_Var_type();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.block <em>block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>block</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.block
   * @generated
   */
  EClass getblock();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.block#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.block#getStatements()
   * @see #getblock()
   * @generated
   */
  EReference getblock_Statements();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.statement <em>statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>statement</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.statement
   * @generated
   */
  EClass getstatement();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.statement#getAtrib_block <em>Atrib block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atrib block</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.statement#getAtrib_block()
   * @see #getstatement()
   * @generated
   */
  EReference getstatement_Atrib_block();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.atrib <em>atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>atrib</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.atrib
   * @generated
   */
  EClass getatrib();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.atrib#getVar_id <em>Var id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var id</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.atrib#getVar_id()
   * @see #getatrib()
   * @generated
   */
  EAttribute getatrib_Var_id();

  /**
   * Returns the meta object for the containment reference '{@link edu.ufcg.compiladores.pascal.pascal.atrib#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.atrib#getExp()
   * @see #getatrib()
   * @generated
   */
  EReference getatrib_Exp();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.expression <em>expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.expression
   * @generated
   */
  EClass getexpression();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.arit_expression <em>arit expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>arit expression</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.arit_expression
   * @generated
   */
  EClass getarit_expression();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.arit_expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.arit_expression#getValue()
   * @see #getarit_expression()
   * @generated
   */
  EAttribute getarit_expression_Value();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.arit_expression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.arit_expression#getExp()
   * @see #getarit_expression()
   * @generated
   */
  EReference getarit_expression_Exp();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression <em>repetitive arit expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>repetitive arit expression</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression
   * @generated
   */
  EClass getrepetitive_arit_expression();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getOp()
   * @see #getrepetitive_arit_expression()
   * @generated
   */
  EAttribute getrepetitive_arit_expression_Op();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getValue()
   * @see #getrepetitive_arit_expression()
   * @generated
   */
  EAttribute getrepetitive_arit_expression_Value();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.repetitive_arit_expression#getExp()
   * @see #getrepetitive_arit_expression()
   * @generated
   */
  EReference getrepetitive_arit_expression_Exp();

  /**
   * Returns the meta object for class '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression <em>rel expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rel expression</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression
   * @generated
   */
  EClass getrel_expression();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression#getOpen <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Open</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression#getOpen()
   * @see #getrel_expression()
   * @generated
   */
  EAttribute getrel_expression_Open();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>First</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression#getFirst()
   * @see #getrel_expression()
   * @generated
   */
  EAttribute getrel_expression_First();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression#getOp()
   * @see #getrel_expression()
   * @generated
   */
  EAttribute getrel_expression_Op();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression#getSecond <em>Second</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Second</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression#getSecond()
   * @see #getrel_expression()
   * @generated
   */
  EAttribute getrel_expression_Second();

  /**
   * Returns the meta object for the attribute '{@link edu.ufcg.compiladores.pascal.pascal.rel_expression#getClose <em>Close</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Close</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.rel_expression#getClose()
   * @see #getrel_expression()
   * @generated
   */
  EAttribute getrel_expression_Close();

  /**
   * Returns the meta object for enum '{@link edu.ufcg.compiladores.pascal.pascal.type <em>type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>type</em>'.
   * @see edu.ufcg.compiladores.pascal.pascal.type
   * @generated
   */
  EEnum gettype();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PascalFactory getPascalFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.PascalImpl <em>Pascal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getPascal()
     * @generated
     */
    EClass PASCAL = eINSTANCE.getPascal();

    /**
     * The meta object literal for the '<em><b>Head</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASCAL__HEAD = eINSTANCE.getPascal_Head();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASCAL__DECLARATIONS = eINSTANCE.getPascal_Declarations();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASCAL__SCOPE = eINSTANCE.getPascal_Scope();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.programImpl <em>program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.programImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getprogram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getprogram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getprogram_Name();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_blockImpl <em>var block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.var_blockImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_block()
     * @generated
     */
    EClass VAR_BLOCK = eINSTANCE.getvar_block();

    /**
     * The meta object literal for the '<em><b>Var statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_BLOCK__VAR_STATEMENTS = eINSTANCE.getvar_block_Var_statements();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl <em>var decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.var_declImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_decl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getvar_decl();

    /**
     * The meta object literal for the '<em><b>Var id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__VAR_ID = eINSTANCE.getvar_decl_Var_id();

    /**
     * The meta object literal for the '<em><b>Var type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__VAR_TYPE = eINSTANCE.getvar_decl_Var_type();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__VALUE = eINSTANCE.getvar_decl_Value();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl <em>var list</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.var_listImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getvar_list()
     * @generated
     */
    EClass VAR_LIST = eINSTANCE.getvar_list();

    /**
     * The meta object literal for the '<em><b>Var id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_LIST__VAR_ID = eINSTANCE.getvar_list_Var_id();

    /**
     * The meta object literal for the '<em><b>Var ids</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_LIST__VAR_IDS = eINSTANCE.getvar_list_Var_ids();

    /**
     * The meta object literal for the '<em><b>Var type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_LIST__VAR_TYPE = eINSTANCE.getvar_list_Var_type();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.blockImpl <em>block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.blockImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getblock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getblock();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STATEMENTS = eINSTANCE.getblock_Statements();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.statementImpl <em>statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.statementImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getstatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getstatement();

    /**
     * The meta object literal for the '<em><b>Atrib block</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__ATRIB_BLOCK = eINSTANCE.getstatement_Atrib_block();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.atribImpl <em>atrib</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.atribImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getatrib()
     * @generated
     */
    EClass ATRIB = eINSTANCE.getatrib();

    /**
     * The meta object literal for the '<em><b>Var id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VAR_ID = eINSTANCE.getatrib_Var_id();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIB__EXP = eINSTANCE.getatrib_Exp();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.expressionImpl <em>expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.expressionImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getexpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getexpression();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.arit_expressionImpl <em>arit expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.arit_expressionImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getarit_expression()
     * @generated
     */
    EClass ARIT_EXPRESSION = eINSTANCE.getarit_expression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARIT_EXPRESSION__VALUE = eINSTANCE.getarit_expression_Value();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARIT_EXPRESSION__EXP = eINSTANCE.getarit_expression_Exp();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.repetitive_arit_expressionImpl <em>repetitive arit expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.repetitive_arit_expressionImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getrepetitive_arit_expression()
     * @generated
     */
    EClass REPETITIVE_ARIT_EXPRESSION = eINSTANCE.getrepetitive_arit_expression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPETITIVE_ARIT_EXPRESSION__OP = eINSTANCE.getrepetitive_arit_expression_Op();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPETITIVE_ARIT_EXPRESSION__VALUE = eINSTANCE.getrepetitive_arit_expression_Value();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPETITIVE_ARIT_EXPRESSION__EXP = eINSTANCE.getrepetitive_arit_expression_Exp();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.impl.rel_expressionImpl <em>rel expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.impl.rel_expressionImpl
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#getrel_expression()
     * @generated
     */
    EClass REL_EXPRESSION = eINSTANCE.getrel_expression();

    /**
     * The meta object literal for the '<em><b>Open</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXPRESSION__OPEN = eINSTANCE.getrel_expression_Open();

    /**
     * The meta object literal for the '<em><b>First</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXPRESSION__FIRST = eINSTANCE.getrel_expression_First();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXPRESSION__OP = eINSTANCE.getrel_expression_Op();

    /**
     * The meta object literal for the '<em><b>Second</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXPRESSION__SECOND = eINSTANCE.getrel_expression_Second();

    /**
     * The meta object literal for the '<em><b>Close</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXPRESSION__CLOSE = eINSTANCE.getrel_expression_Close();

    /**
     * The meta object literal for the '{@link edu.ufcg.compiladores.pascal.pascal.type <em>type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ufcg.compiladores.pascal.pascal.type
     * @see edu.ufcg.compiladores.pascal.pascal.impl.PascalPackageImpl#gettype()
     * @generated
     */
    EEnum TYPE = eINSTANCE.gettype();

  }

} //PascalPackage
