/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.idea.highlighting;

import edu.ufcg.compiladores.pascal.idea.highlighting.PascalBaseColorSettingsPage;

@SuppressWarnings("all")
public class PascalColorSettingsPage extends PascalBaseColorSettingsPage {
}
