/*
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.ide.contentassist.antlr;

import com.google.inject.Inject;
import edu.ufcg.compiladores.pascal.ide.contentassist.antlr.internal.InternalPascalParser;
import edu.ufcg.compiladores.pascal.services.PascalGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class PascalParser extends AbstractContentAssistParser {

	@Inject
	private PascalGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPascalParser createParser() {
		InternalPascalParser result = new InternalPascalParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSomeValueAccess().getAlternatives(), "rule__SomeValue__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getPascalAccess().getGroup(), "rule__Pascal__Group__0");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getVar_declAccess().getGroup(), "rule__Var_decl__Group__0");
					put(grammarAccess.getVar_declAccess().getGroup_1(), "rule__Var_decl__Group_1__0");
					put(grammarAccess.getVar_listAccess().getGroup(), "rule__Var_list__Group__0");
					put(grammarAccess.getVar_listAccess().getGroup_1(), "rule__Var_list__Group_1__0");
					put(grammarAccess.getAtribAccess().getGroup(), "rule__Atrib__Group__0");
					put(grammarAccess.getPascalAccess().getElementAssignment_0(), "rule__Pascal__ElementAssignment_0");
					put(grammarAccess.getPascalAccess().getElementAssignment_1(), "rule__Pascal__ElementAssignment_1");
					put(grammarAccess.getPascalAccess().getElementAssignment_2(), "rule__Pascal__ElementAssignment_2");
					put(grammarAccess.getProgramAccess().getNameAssignment_1(), "rule__Program__NameAssignment_1");
					put(grammarAccess.getVar_declAccess().getVar_listAssignment_1_0(), "rule__Var_decl__Var_listAssignment_1_0");
					put(grammarAccess.getVar_declAccess().getTypeAssignment_1_2(), "rule__Var_decl__TypeAssignment_1_2");
					put(grammarAccess.getVar_listAccess().getIdentifierAssignment_0(), "rule__Var_list__IdentifierAssignment_0");
					put(grammarAccess.getVar_listAccess().getVar_listAssignment_1_1(), "rule__Var_list__Var_listAssignment_1_1");
					put(grammarAccess.getAtribAccess().getIdentifierAssignment_0(), "rule__Atrib__IdentifierAssignment_0");
					put(grammarAccess.getAtribAccess().getValueAssignment_2(), "rule__Atrib__ValueAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalPascalParser typedParser = (InternalPascalParser) parser;
			typedParser.entryRulePascal();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PascalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PascalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
