/**
 * generated by Xtext 2.9.0
 */
package edu.ufcg.compiladores.pascal.scoping;

import edu.ufcg.compiladores.pascal.scoping.AbstractPascalScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PascalScopeProvider extends AbstractPascalScopeProvider {
}
